options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://gen-lang-client-0039862552-cloudbuild-logs

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-image-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-image-app:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ai-image-app
      - --image
      - gcr.io/$PROJECT_ID/ai-image-app:$COMMIT_SHA
      - --region
      - asia-southeast1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/ai-image-app:$COMMIT_SHA
